### ISSUE TITLE
Update to 1.9.17 and 1.0.10

### ISSUE THREAD

**Issue by gdevenyi** [BIC-MNI/BIC-MNI.github.io#3]
Versions need updating. I see the packages are available for download.

I'm going to do this manually, but if you have any automation @vfonov I'll leave it to you.

Do we have an OSX build?

**Comment by vfonov** [comment]
Not yet, for the OsX built.

**Comment by vfonov** [comment]
I don't have any automation for making releases, just manually update https://github.com/BIC-MNI/BIC-MNI.github.io
